package:
  name: ros2-distro-mutex
  version: 0.1.0

build:
  number: 1
  # Note: keep in sync with build number
  # Cannot be done automatically, see https://github.com/mamba-org/boa/issues/278
  string: rolling_1

requirements:
  # NOTE:
  # The idea with automatically adding versions to run_exports doesn't
  # work since we don't want all these dependencies as run deps of all ROS
  # packages. Therefore I am currently manually adding them to run_constrained.
  # This has to be synchronized with our current conda_build_config all the time :(
  # host:
  #   # values here should
  #   - log4cxx
  #   - poco
  #   - pcl
  #   - opencv
  #   - gazebo
  #   - ogre
  #   - qt
  # run:
  # values here should be applied from run_exports!
  # if the upstream package does not have run_exports
  # please change it in the conda_build_config.yaml!
  run_constraints:
    - libboost 1.86.*
    - libboost-devel 1.86.*
    - pcl 1.15.0.*
    - gazebo 11.*
    - libprotobuf 5.29.3.*
    - libxml2 2.13.*
    - vtk 9.4.2.*

  run_exports:
    weak:
      - ${{ pin_subpackage('ros2-distro-mutex', upper_bound='x.x') }}


about:
  homepage: https://github.com/robostack/ros-rolling
  license: BSD-3-Clause
  summary: |
    The ROS2 distro mutex. To switch between ROS2 versions, you need to change the mutex.
    E.g. mamba install ros2-distro-mutex=*=rolling to switch to rolling.

extra:
  recipe-maintainers:
    - ros-forge

