numpy:
  - 1.26
libprotobuf:
  - 5.29.3
protobuf:
  - 5.29.3
spdlog:
  - 1.15
pugixml:
  - '1.15'
libopencv:
  - 4.11.0
libxml2:
  - 2.13.*

# Workaround for https://github.com/RoboStack/ros-kilted/pull/40#issuecomment-2782226697
cmake:
  - 3.* 

cdt_name:  # [linux]
  - conda  # [linux]

python:
  - 3.12.* *_cpython
python_impl:
  - cpython

c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2019                     # [win and x86_64]
  - vs2022                     # [win and arm64]
c_compiler_version:            # [unix]
  - 13                         # [linux]
  - 18                         # [osx]
c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 10.13                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2019                     # [win and x86_64]
  - vs2022                     # [win and arm64]
cxx_compiler_version:          # [unix]
  - 13                         # [linux]
  - 18                         # [osx]

libzenohc:
  - 1.3.4
libzenohcxx:
  - 1.3.4
libcap:
  - 2.71
