[project]
name = "ros-rolling"
description = "RoboStack repo to package ros-rolling packages as conda packages"
authors = ["Tobias Fischer <tobias.fischer@qut.edu.au>", "Wolf Vollprecht <w.vollprecht@gmail.com>", "Silvio Traversaro <silvio@traversaro.it>"]
channels = ["https://repo.prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64", "linux-aarch64", "win-64"]

[system-requirements]
# 2.17 is the glibc version used in centos 7
libc = { family="glibc", version="2.17" }

[tasks]
upload = "anaconda -t $ANACONDA_API_TOKEN upload"

[dependencies]
python = ">=3.12.0,<3.13"
rattler-build = ">=0.35.5"
anaconda-client = ">=1.13.0"
cmake = "<4.0"

[target.win-64.dependencies]
# patch is required by rattler-build
m2-patch = "*"
# git is required by rattler-build
git = "*"

[feature.beta.pypi-dependencies]
# This is tipically the latest commit on main branch
vinca = { git ="https://github.com/RoboStack/vinca.git", rev = "cbb8eba834ce3834df552977d6b08c325a30768e" }
# Uncomment this line to work with a local vinca for faster iteration, but remember to comment it back
# (and regenerate the pixi.lock) once you push the modified commit to the repo
#vinca = { path = "../vinca", editable = true }

[feature.beta.tasks]
generate-recipes = { cmd = "vinca -m", depends-on = ["rename-file"] }
remove-file = { cmd = "rm vinca.yaml; rm -rf recipes; mkdir recipes" }
build_additional_recipes = { cmd = "rattler-build build --recipe-dir ./additional_recipes -m ./conda_build_config.yaml --skip-existing -c robostack-rolling -c https://repo.prefix.dev/conda-forge", depends-on = ["generate-recipes"] }
build = { cmd = "rattler-build build --recipe-dir ./recipes -m ./conda_build_config.yaml -c robostack-rolling -c https://repo.prefix.dev/conda-forge --skip-existing", depends-on = ["build_additional_recipes", "generate-recipes"] }
build_one_package = { cmd = "cp ./patch/$PACKAGE.*patch ./recipes/$PACKAGE/patch/; rattler-build build --recipe ./recipes/$PACKAGE/recipe.yaml -m ./conda_build_config.yaml -c robostack-rolling -c https://repo.prefix.dev/conda-forge", env = { PACKAGE = "ros-rolling-ros-workspace" } }
create_snapshot = { cmd = "vinca-snapshot -d rolling -o rosdistro_snapshot.yaml" }

[environments]
beta = ["beta"]

[target.linux-64.tasks]
rename-file = { cmd = "ln -s vinca_linux_64.yaml vinca.yaml", depends-on = ["remove-file"] }

[target.osx-64.tasks]
rename-file = { cmd = "ln -s vinca_osx.yaml vinca.yaml", depends-on = ["remove-file"] }

[target.osx-arm64.tasks]
rename-file = { cmd = "ln -s vinca_osx_arm64.yaml vinca.yaml", depends-on = ["remove-file"] }

[target.linux-aarch64.tasks]
rename-file = { cmd = "ln -s vinca_linux_aarch64.yaml vinca.yaml", depends-on = ["remove-file"] }

[target.win-64.tasks]
rename-file = { cmd = "cp vinca_win.yaml vinca.yaml", depends-on = ["remove-file"] }
