package:
  name: ros-rolling-urdfdom-py
  version: "1.2.1"

build:
  number: 5

requirements:
  run:
    - urdfdom-py 1.2.1.*
    - python 3.12.* *_cpython

about:
  homepage: https://github.com/ros/urdf_parser_py
  license: BSD-3-Clause
  summary: |
    Standalone URDF parser for Python.
extra:
  recipe-maintainers:
    - ros-forge
